# Generated by Django 3.1 on 2021-06-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebase_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='text_name',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
    ]
